project:
  type: website

website:
  favicon: img/DJredscare_icon.png
  navbar:
    search: false
    left:
      - href: about.qmd
        text: About
      - projects.qmd
      - hobbies.qmd
    tools:
      - icon: envelope
        href: mailto:charlesskopp@gmail.com
      - icon: linkedin
        href: https://www.linkedin.com/in/charlie-kopp/
      - icon: github
        href:  https://github.com/charlemagnethaging

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [sandstone, custom.scss]
      dark: [sandstone, custom.scss]
    css: styles.css
    toc: true



